"""Kernels and scalable kernel methods for JAX.

``kernellib`` sits between `gaussx <https://github.com/jejjohnson/gaussx>`_
(structured linear operators, solvers, preconditioners) and
`pyrox-gp <https://github.com/jejjohnson/pyrox>`_ (Gaussian-process models
with NumPyro priors). It owns kernel functions and their composition, spectral
densities and feature maps, kernel ridge regression, dependence measures, and
kernel derivatives. Scale is inherited from gaussx: every kernel can be turned
into a gaussx linear operator, and every algorithm here solves through gaussx's
solver strategies.

The package never imports ``numpyro``; the modelling layer above it does.

Everything listed in ``__all__`` is importable straight from the top-level
package.
"""

from __future__ import annotations

from kernellib import functional
from kernellib._decomposition import (
    KernelLocalityPreservingProjections,
    KernelPCA,
    KernelSchrodingerProjections,
    LaplacianEigenmaps,
    LocalityPreservingProjections,
    SchrodingerEigenmapProjections,
    SchrodingerEigenmaps,
    barrier_potential,
    combine_potentials,
    label_potential,
    laplacian_eigenmap,
    schrodinger_eigenmap,
    spatial_spectral_graph,
    spatial_spectral_potential,
)
from kernellib._dependence import (
    CKAAccumulator,
    PermutationTestResult,
    TaylorStatistics,
    cka,
    distance_correlation_squared,
    distance_covariance_squared,
    energy_distance,
    hsic,
    kernel_alignment,
    mmd_squared,
    permutation_test,
    taylor_statistics,
)
from kernellib._geo import (
    AbstractGreatCircleKernel,
    Chordal,
    GreatCircleAskey,
    GreatCircleCauchy,
    GreatCircleExponential,
    GreatCirclePoweredExponential,
    GreatCircleSpherical,
    GreatCircleWendland,
)
from kernellib._graph import (
    AbstractGraph,
    Graph,
    GraphTopology,
    GridGraph,
    KNNGraph,
    adjacency_matrix,
    commute_time_kernel,
    cosine_graph_kernel,
    delaunay_graph,
    diffusion_kernel,
    edge_weights,
    gabriel_graph,
    graph_from_adjacency,
    graph_from_edges,
    graph_from_neighbors,
    graph_laplacian,
    graph_null_space,
    grid_graph,
    knn_graph,
    laplacian_eigpairs,
    matern_graph_kernel,
    mesh_graph,
    n_components_graph,
    nearest_neighbors,
    radius_graph,
    radius_neighbors,
    random_walk_kernel,
    regularized_laplacian_kernel,
    relative_neighborhood_graph,
    structure_matrix,
)
from kernellib._heuristics import (
    estimate_lengthscale,
    gamma_to_lengthscale,
    lengthscale_grid,
    lengthscale_to_gamma,
)
from kernellib._kernels import (
    RBF,
    AbstractKernel,
    AbstractPointwiseKernel,
    AbstractStationaryKernel,
    ActiveDims,
    Constant,
    Cosine,
    Derivative,
    DerivativeIndexed,
    Distance,
    FeatureKernel,
    Linear,
    Matern,
    Modulated,
    Periodic,
    Periodised,
    Polynomial,
    Product,
    RationalQuadratic,
    Residual,
    Scaled,
    Shift,
    Stretch,
    Sum,
    Warped,
    White,
    derivative_inputs,
    nystrom_kernel,
)
from kernellib._operators import (
    FastFoodParams,
    ImplicitCrossKernelOperator,
    ImplicitKernelOperator,
    KernelOperator,
    batched_kernel_matvec,
    batched_kernel_rmatvec,
    fastfood_features,
    fastfood_frequencies,
    fastfood_operator,
    fastfood_params,
    hadamard_transform,
    implicit_cross_kernel,
    nystrom_operator,
    rff_operator,
    to_cross_operator,
    to_operator,
)
from kernellib._regression import (
    KRR,
    AbstractEstimator,
    EigenPro,
    EigenProPreconditioner,
    Falkon,
    FalkonInfo,
    FalkonPreconditioner,
    eigenpro_correction,
    eigenpro_preconditioner,
    eigenpro_step_size,
    falkon_preconditioner,
    falkon_predict,
    falkon_solve,
    hsic_penalty,
    laplacian_penalty,
)
from kernellib._spectral import (
    AbstractFeatureMap,
    FastFoodFeatures,
    LaplaceEigenfunctionFeatures,
    NystromFeatures,
    OrthogonalRandomFeatures,
    RandomFourierFeatures,
    draw_rff_cosine_basis,
    evaluate_rff_cosine_paths,
    select_landmarks,
)
from kernellib.functional._geo import EARTH_RADIUS_KM


__version__ = "0.0.18"

from kernellib._geo import (
    Cubic,
    GeneralizedCauchy,
    HoleEffect,
    Pentaspherical,
    Spherical,
    Stable,
    Wendland,
)


__all__ = [
    "EARTH_RADIUS_KM",
    "KRR",
    "RBF",
    "AbstractEstimator",
    "AbstractFeatureMap",
    "AbstractGraph",
    "AbstractGreatCircleKernel",
    "AbstractKernel",
    "AbstractPointwiseKernel",
    "AbstractStationaryKernel",
    "ActiveDims",
    "CKAAccumulator",
    "Chordal",
    "Constant",
    "Cosine",
    "Cubic",
    "Derivative",
    "DerivativeIndexed",
    "Distance",
    "EigenPro",
    "EigenProPreconditioner",
    "Falkon",
    "FalkonInfo",
    "FalkonPreconditioner",
    "FastFoodFeatures",
    "FastFoodParams",
    "FeatureKernel",
    "GeneralizedCauchy",
    "Graph",
    "GraphTopology",
    "GreatCircleAskey",
    "GreatCircleCauchy",
    "GreatCircleExponential",
    "GreatCirclePoweredExponential",
    "GreatCircleSpherical",
    "GreatCircleWendland",
    "GridGraph",
    "HoleEffect",
    "ImplicitCrossKernelOperator",
    "ImplicitKernelOperator",
    "KNNGraph",
    "KernelLocalityPreservingProjections",
    "KernelOperator",
    "KernelPCA",
    "KernelSchrodingerProjections",
    "LaplaceEigenfunctionFeatures",
    "LaplacianEigenmaps",
    "Linear",
    "LocalityPreservingProjections",
    "Matern",
    "Modulated",
    "NystromFeatures",
    "OrthogonalRandomFeatures",
    "Pentaspherical",
    "Periodic",
    "Periodised",
    "PermutationTestResult",
    "Polynomial",
    "Product",
    "RandomFourierFeatures",
    "RationalQuadratic",
    "Residual",
    "Scaled",
    "SchrodingerEigenmapProjections",
    "SchrodingerEigenmaps",
    "Shift",
    "Spherical",
    "Stable",
    "Stretch",
    "Sum",
    "TaylorStatistics",
    "Warped",
    "Wendland",
    "White",
    "__version__",
    "adjacency_matrix",
    "barrier_potential",
    "batched_kernel_matvec",
    "batched_kernel_rmatvec",
    "cka",
    "combine_potentials",
    "commute_time_kernel",
    "cosine_graph_kernel",
    "delaunay_graph",
    "derivative_inputs",
    "diffusion_kernel",
    "distance_correlation_squared",
    "distance_covariance_squared",
    "draw_rff_cosine_basis",
    "edge_weights",
    "eigenpro_correction",
    "eigenpro_preconditioner",
    "eigenpro_step_size",
    "energy_distance",
    "estimate_lengthscale",
    "evaluate_rff_cosine_paths",
    "falkon_preconditioner",
    "falkon_predict",
    "falkon_solve",
    "fastfood_features",
    "fastfood_frequencies",
    "fastfood_operator",
    "fastfood_params",
    "functional",
    "gabriel_graph",
    "gamma_to_lengthscale",
    "graph_from_adjacency",
    "graph_from_edges",
    "graph_from_neighbors",
    "graph_laplacian",
    "graph_null_space",
    "grid_graph",
    "hadamard_transform",
    "hsic",
    "hsic_penalty",
    "implicit_cross_kernel",
    "kernel_alignment",
    "knn_graph",
    "label_potential",
    "laplacian_eigenmap",
    "laplacian_eigpairs",
    "laplacian_penalty",
    "lengthscale_grid",
    "lengthscale_to_gamma",
    "matern_graph_kernel",
    "mesh_graph",
    "mmd_squared",
    "n_components_graph",
    "nearest_neighbors",
    "nystrom_kernel",
    "nystrom_operator",
    "permutation_test",
    "radius_graph",
    "radius_neighbors",
    "random_walk_kernel",
    "regularized_laplacian_kernel",
    "relative_neighborhood_graph",
    "rff_operator",
    "schrodinger_eigenmap",
    "select_landmarks",
    "spatial_spectral_graph",
    "spatial_spectral_potential",
    "structure_matrix",
    "taylor_statistics",
    "to_cross_operator",
    "to_operator",
]
